from enum import Enum

class Substats(Enum):
    # Normal stats
    ATK_PERCENT = "ATK_PERCENT"
    ATK_FLAT = "ATK_FLAT"
    DEF_PERCENT = "DEF_PERCENT"
    DEF_FLAT = "DEF_FLAT"
    HP_PERCENT = "HP_PERCENT"
    HP_FLAT = "HP_FLAT"
    CRIT_RATE = "CRIT_RATE"
    CRIT_DMG = "CRIT_DMG"
    ENERGY_REGEN = "ENERGY_REGENERATION"

    # Attack type bonuses
    RESONANCE_SKILL = "RESONANCE_SKILL_DMG"
    RESONANCE_LIBERATION = "RESONANCE_LIBERATION_DMG"
    HEAVY_ATTACK_DMG = "HEAVY_ATTACK_DMG"
    BASIC_ATTACK_DMG = "RESONANCE_SKILL_DMG"